export ANTHROPIC_BASE_URL="http://113.57.198.109:4000/litellm"
unset ANTHROPIC_AUTH_TOKEN
export ANTHROPIC_API_KEY="sk-adcoHDS1TZZIQFxgqxBdfA"
export ANTHROPIC_DEFAULT_SONNET_MODEL=glm5.1
export ANTHROPIC_DEFAULT_HAIKU_MODEL=glm5.1
export ANTHROPIC_DEFAULT_OPUS_MODEL=glm5.1
export CLAUDE_CODE_SUBAGENT_MODEL=glm5.1

